import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export const LogTable = ({ logs }) => {
    return (_jsx("div", { className: "flex flex-col", children: _jsx("div", { className: "-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8", children: _jsx("div", { className: "py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8", children: _jsx("div", { className: "shadow-2xl overflow-hidden border border-white/10 rounded-[24px] backdrop-blur-xl bg-white/5", children: _jsxs("table", { className: "min-w-full divide-y divide-white/10", children: [_jsx("thead", { className: "bg-white/5", children: _jsxs("tr", { children: [_jsx("th", { scope: "col", className: "px-6 py-4 text-left text-xs font-bold text-white/70 uppercase tracking-wider", children: "Status" }), _jsx("th", { scope: "col", className: "px-6 py-4 text-left text-xs font-bold text-white/70 uppercase tracking-wider", children: "Message" }), _jsx("th", { scope: "col", className: "px-6 py-4 text-left text-xs font-bold text-white/70 uppercase tracking-wider", children: "Time" })] }) }), _jsxs("tbody", { className: "divide-y divide-white/10", children: [logs.map((log) => (_jsxs("tr", { className: "hover:bg-white/5 transition-colors duration-200", children: [_jsx("td", { className: "px-6 py-4 whitespace-nowrap", children: _jsx("span", { className: `px-3 py-1 inline-flex text-xs leading-5 font-bold rounded-full ${log.status === 'SUCCESS'
                                                        ? 'bg-[#00F5A0]/20 text-[#00F5A0] border border-[#00F5A0]/30'
                                                        : log.status === 'FAILURE'
                                                            ? 'bg-[#FF2E63]/20 text-[#FF2E63] border border-[#FF2E63]/30'
                                                            : log.status === 'SKIPPED'
                                                                ? 'bg-yellow-500/20 text-yellow-400 border border-yellow-500/30'
                                                                : 'bg-blue-500/20 text-blue-400 border border-blue-500/30'}`, children: log.status }) }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm text-white/90", children: log.message }), _jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm text-white/60", children: new Date(log.created_at).toLocaleString() })] }, log.id))), logs.length === 0 && (_jsx("tr", { children: _jsx("td", { colSpan: 3, className: "px-6 py-8 text-center text-sm text-white/50", children: "No logs found." }) }))] })] }) }) }) }) }));
};
