import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Button } from '@atomaton/ui';
import { useWorkflowStore } from '../store/workflowStore';
import { GlobalSettingsModal } from './GlobalSettingsModal';
export const Sidebar = ({ onSave, onTest }) => {
    const isValid = useWorkflowStore((state) => state.isValid);
    const [isSettingsOpen, setIsSettingsOpen] = useState(false);
    const onDragStart = (event, nodeType) => {
        event.dataTransfer.setData('application/reactflow', nodeType);
        event.dataTransfer.effectAllowed = 'move';
    };
    return (_jsxs("aside", { className: "w-64 bg-white/5 backdrop-blur-xl border-r border-white/10 p-4 flex flex-col gap-4 z-20", children: [_jsx("div", { className: "text-lg font-bold text-white mb-2", children: "Workflow" }), _jsxs("div", { className: "space-y-2", children: [_jsx(Button, { variant: "secondary", onClick: onSave, disabled: !isValid, className: "w-full", children: "Save" }), _jsx(Button, { onClick: onTest, className: "w-full", children: "Run Test" }), _jsx("button", { onClick: () => setIsSettingsOpen(true), className: "w-full py-2 text-sm text-white/70 hover:text-white hover:bg-white/10 rounded border border-white/20 transition-colors", children: "Global Settings" })] }), _jsx("hr", { className: "my-4 border-white/10" }), _jsx("div", { className: "text-sm font-bold text-white/50 uppercase", children: "Toolbox" }), _jsxs("div", { children: [_jsx("div", { className: "text-xs font-semibold text-[#8A3FFC] mb-2", children: "Triggers" }), _jsx("div", { className: "p-3 bg-white/5 border border-white/10 rounded-xl cursor-grab mb-2 hover:bg-white/10 hover:border-[#8A3FFC]/50 transition-all text-white text-sm", onDragStart: (event) => onDragStart(event, 'trigger'), draggable: true, children: "IMAP Email" }), _jsx("div", { className: "p-3 bg-white/5 border border-white/10 rounded-xl cursor-grab mb-2 hover:bg-white/10 hover:border-[#8A3FFC]/50 transition-all text-white text-sm", onDragStart: (event) => onDragStart(event, 'trigger-webhook'), draggable: true, children: "Incoming Webhook" })] }), _jsxs("div", { children: [_jsx("div", { className: "text-xs font-semibold text-[#E02DFF] mb-2", children: "Logic" }), _jsx("div", { className: "p-3 bg-white/5 border border-white/10 rounded-xl cursor-grab mb-2 hover:bg-white/10 hover:border-[#E02DFF]/50 transition-all text-white text-sm", onDragStart: (event) => onDragStart(event, 'condition'), draggable: true, children: "Condition (If/Else)" })] }), _jsxs("div", { children: [_jsx("div", { className: "text-xs font-semibold text-[#00F5A0] mb-2", children: "Actions" }), _jsx("div", { className: "p-3 bg-white/5 border border-white/10 rounded-xl cursor-grab mb-2 hover:bg-white/10 hover:border-[#00F5A0]/50 transition-all text-white text-sm", onDragStart: (event) => onDragStart(event, 'action'), draggable: true, children: "Discord Webhook" }), _jsx("div", { className: "p-3 bg-white/5 border border-white/10 rounded-xl cursor-grab mb-2 hover:bg-white/10 hover:border-[#00F5A0]/50 transition-all text-white text-sm", onDragStart: (event) => onDragStart(event, 'action-notion'), draggable: true, children: "Notion Page" })] }), _jsx(GlobalSettingsModal, { isOpen: isSettingsOpen, onClose: () => setIsSettingsOpen(false) })] }));
};
